version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/kubectl
            kubectl
      - run:
          name: Installing Az Cli
          command: |
            echo "deb https://packages.microsoft.com/repos/azure-cli/ wheezy main" | tee /etc/apt/sources.list.d/azure-cli.list
            apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
            # echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | tee /etc/apt/sources.list.d/azure-cli.list
            apt-get install apt-transport-https
            apt-get update && apt-get install azure-cli
      - run:
          name: az
          command: az
      - run:
          name: building dotnet 
          command: dotnet build ./AzSp.Products/AzSp.Products.csproj -c Release
      - run:
          name: publish dotnet 
          command: dotnet publish ./AzSp.Products/AzSp.Products.csproj -c Release -o ./obj/Docker/publish
      - run:
          name: docker build and push
          command: | 
            TAG=1.$CIRCLE_BUILD_NUM
            docker build -t azsp.products ./AzSp.Products/.
            docker tag azsp.products $DOCKER_REGISTRY/azsp.products:$TAG
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_REGISTRY/azsp.products:$TAG
        
        
    