version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: ls
          command: ls
      - run:
          name: building dotnet 
          command: dotnet build ./AzSp.Products/AzSp.Products.csproj -c Release
      - run:
          name: publish dotnet 
          command: dotnet publish ./AzSp.Products/AzSp.Products.csproj -c Release -o ./obj/Docker/publish
      - run:
          name: docker build
          command: docker build -t azsp.products ./AzSp.Products/.
      - run:
          name: docker tag
          command: docker tag azsp.products azuresuperpowers.azurecr.io/azsp.products
      - run:
          name: docker push
          command: docker push azuresuperpowers.azurecr.io/azsp.products
        
        
    