apiVersion: v1
kind: Service
metadata:
  name: lbproducts
  labels:
    name: lbproducts
spec:
  selector:
    service: products
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP